### PR TITLE
updated provision-deep-learning-dsvm.md

### PR DESCRIPTION
**Pull request by italojs**
I noted that didn't have a direct link to basic ssh VM access, so I updated this .md with basic ssh documentation link for Azure VM access for those that were getting started with Azure VM.

If something are wrong, please, do not close this PR, write a comment so I will fix it.

tks

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @italojs  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by italojs** [comment]
conflict resolved

**Comment by italojs** [comment]
someone can merge this PR? :)

**Comment by v-radelg** [comment]
@italojs :
Thank you for your feedback and suggestion!
We agree with your suggestions, and we will include them into the next article update release.
Thank you for your time and support. 
Microsoft C&E Localization Team

**Pull request merged**
