### PR TITLE
Fix mistranslation

### PR DESCRIPTION
**Pull request by changeworld**
Should not translate proper nouns.

### CODE REVIEW

**Comment by srvbpigh** [comment]
Hello, @changeworld:

Thank you for your contribution! We are processing your suggestions and we will update you shortly.  


Kind regards, 

Microsoft DOCS Global Experience Team

**Comment by srvbpigh** [comment]
@changeworld,

Agradecemos novamente suas sugestões! Concordamos com você e faremos a mesclagem desta PR. A sugestão também será usada na próxima atualização do artigo.


Atenciosamente,

Equipe do DOCS Global Experience da Microsoft

**Comment by ticianaciminari** [comment]
@changeworld:



Thank you again for your suggestions! We agree with them and we will merge this PR. The suggestion will also be used in the next article update.



Kind regards, 



Microsoft DOCS Global Experience Team

**Comment by ticianaciminari** [comment]
@changeworld:



Thank you again for your suggestions! We agree with them and we will merge this PR. The suggestion will also be used in the next article update.



Kind regards, 



Microsoft DOCS Global Experience Team

**Pull request merged**
